// LOAD ALL THE COMPONENTS FROM DOCUMENT HERE

// ADD EVENT LISTENERS TO CALL FUNCTIONS(IF ANY)

// ADD FUNCTIONS HERE

//ADD MAIN LOGIC FUNCTION HERE

//USE setTimeInterval(function(), time in ms) in place of onData
